apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{ include "web-app.base_labels" . | indent 2 }}
type: Opaque
data:
  RAILS_MASTER_KEY: {{ .Values.secrets.rails_master_key | b64enc | quote }}