apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{ include "web-app.base_labels" . | indent 2 }}
    {{ include "web-app.selector_labels" . | indent 2 }}
  annotations:
    {{ include "web-app.managed_cert_annotations" . | indent 2 }}
spec:
  defaultBackend:
    service:
      name: "{{ .Release.Name }}-{{ .Values.service.type | lower }}"
      port:
        number: {{ .Values.service.port }}