apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    {{ include "web-app.base_labels" . | indent 2 }}
spec:
    minAvailable: {{ .Values.pdb.minAvailable }}
    selector:
      matchLabels:
      {{- include "web-app.selector_labels" . | indent 6 }}