apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
spec:
  targetRef:
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies: []
